"""
mqtt/alert_engine.py
====================
Evaluates every detection event against a set of rules and generates alerts.

Rules (in priority order):
  HIGH   — No Remote ID broadcast (drone_id present but no operator_id)
  HIGH   — Unknown drone type or spoofed-looking coordinates
  MEDIUM — Speed > threshold (configurable, default 30 m/s)
  MEDIUM — Altitude > 400ft AGL without operator ID
  MEDIUM — Drone visible to only one node at suspicious altitude
  LOW    — New drone first detection
  LOW    — Node offline (generated by status handler, not here)

Alert deduplication:
  An alert for a given (category, drone_id) is suppressed if the same
  alert was generated within alert_dedup_window_s seconds.
"""

import logging
import time
from collections import defaultdict

from core.config import Settings, get_settings
from db.database import get_pool
from integrations.algo_notifier import AlgoNotifier
from models.schemas import DetectionEvent, NodeHeartbeat
from mqtt.ws_broadcaster import WSBroadcaster

log = logging.getLogger("alerts")

# Module-level singleton — disabled (zero overhead) when ALGO_8128_ENABLED=false
_algo = AlgoNotifier(get_settings())

# 400 ft in meters
FAA_MAX_ALT_M = 121.92


class AlertEngine:
    def __init__(self, settings: Settings):
        self.settings = settings
        self.broadcaster = WSBroadcaster()
        # Dedup: (category, drone_id, node_id) → last_alerted timestamp
        self._dedup: dict[tuple, float] = defaultdict(float)
        self._last_dedup_cleanup: float = 0.0

    def _cleanup_dedup(self) -> None:
        """Purge stale dedup entries every 5 minutes to prevent unbounded growth."""
        now = time.time()
        if now - self._last_dedup_cleanup < 300:
            return
        self._last_dedup_cleanup = now
        cutoff = now - self.settings.alert_dedup_window_s
        stale = [k for k, v in self._dedup.items() if v < cutoff]
        for k in stale:
            del self._dedup[k]

    async def evaluate(self, event: DetectionEvent):
        """Run all rules against a detection event."""
        self._cleanup_dedup()
        drone = event.drone
        alerts = []

        # ---- Rule 1: No Remote ID ----
        # Drone is broadcasting but has no operator ID
        if not drone.operator_id or not drone.operator_id.strip():
            agl = drone.height_agl or 0.0
            if agl >= self.settings.alert_no_rid_min_alt_m:
                alerts.append({
                    "level": "high",
                    "category": "no_rid",
                    "title": f"No Remote ID — {drone.id}",
                    "description": (
                        f"Drone {drone.id} at {agl:.0f}m AGL has no operator ID. "
                        f"Detected via {event.transport} by {event.node_id}. "
                        f"RSSI={event.rssi} dBm."
                    ),
                    "drone_id": drone.id,
                    "node_id": event.node_id,
                    "lat": drone.lat,
                    "lon": drone.lon,
                })

        # ---- Rule 2: Speed anomaly ----
        if drone.speed_h and drone.speed_h > self.settings.alert_speed_threshold_ms:
            alerts.append({
                "level": "medium",
                "category": "speed",
                "title": f"Speed anomaly — {drone.id}",
                "description": (
                    f"Drone {drone.id} reporting {drone.speed_h:.1f} m/s "
                    f"({drone.speed_h * 2.237:.0f} mph) — above threshold "
                    f"of {self.settings.alert_speed_threshold_ms} m/s."
                ),
                "drone_id": drone.id,
                "node_id": event.node_id,
                "lat": drone.lat,
                "lon": drone.lon,
            })

        # ---- Rule 3: Above FAA 400ft limit without operator ID ----
        alt_agl = drone.height_agl or drone.alt_baro or 0.0
        if alt_agl > FAA_MAX_ALT_M and not drone.operator_id:
            alerts.append({
                "level": "medium",
                "category": "altitude",
                "title": f"Above 400ft AGL, no operator ID — {drone.id}",
                "description": (
                    f"Drone {drone.id} at {alt_agl:.0f}m AGL "
                    f"({alt_agl * 3.281:.0f}ft) — exceeds 400ft without waiver ID."
                ),
                "drone_id": drone.id,
                "node_id": event.node_id,
                "lat": drone.lat,
                "lon": drone.lon,
            })

        # ---- Rule 4: Coordinate sanity check (basic spoof detection) ----
        if drone.lat == 0.0 and drone.lon == 0.0 and (drone.height_agl or 0) > 10:
            alerts.append({
                "level": "high",
                "category": "spoofed_position",
                "title": f"Null island coordinates — {drone.id}",
                "description": (
                    f"Drone {drone.id} reporting lat=0, lon=0 while airborne "
                    f"({(drone.height_agl or 0):.0f}m AGL) — likely spoofed position."
                ),
                "drone_id": drone.id,
                "node_id": event.node_id,
                "lat": drone.lat,
                "lon": drone.lon,
            })

        # ---- Rule 5: New drone first seen ----
        pool = await get_pool()
        async with pool.acquire() as conn:
            row = await conn.fetchrow(
                """SELECT detection_count,
                          EXTRACT(EPOCH FROM (NOW() - last_seen)) AS quiet_seconds
                   FROM drone_tracks WHERE drone_id = $1""",
                drone.id
            )
            if row and row["detection_count"] == 1:
                alerts.append({
                    "level": "low",
                    "category": "new_drone",
                    "title": f"New drone detected — {drone.id}",
                    "description": (
                        f"First detection of {drone.id} ({drone.ua_type or 'unknown type'}) "
                        f"via {event.transport} on {event.node_id}."
                    ),
                    "drone_id": drone.id,
                    "node_id": event.node_id,
                    "lat": drone.lat,
                    "lon": drone.lon,
                })

            # If drone was quiet > 60 s, treat as re-appearance: reset strobe state
            # so the trigger logic below starts fresh rather than applying cooldown.
            quiet_s = row["quiet_seconds"] if row and row["quiet_seconds"] else 0
            if quiet_s > 60 and _algo.get_drone_level(drone.id):
                await _algo.clear()
                _algo.clear_drone_state(drone.id)

        # Write and broadcast all generated alerts (dedup checked here)
        emitted: list[dict] = []
        for alert in alerts:
            key = (alert["category"], alert.get("drone_id"), alert.get("node_id"))
            now_ts = time.time()
            if now_ts - self._dedup[key] < self.settings.alert_dedup_window_s:
                continue
            self._dedup[key] = now_ts
            await self._emit(alert)
            emitted.append(alert)

        # ---- Algo 8128 strobe logic ----
        # Determine the highest threat level emitted for this drone in this batch.
        _rank = {"low": 0, "medium": 1, "high": 2}
        drone_id = event.drone.id
        drone_emitted = [a for a in emitted if a.get("drone_id") == drone_id]
        if drone_emitted:
            top_level = max(drone_emitted, key=lambda a: _rank.get(a["level"], -1))["level"]
            await _algo.trigger(top_level, drone_id)
        elif _algo.get_drone_level(drone_id):
            # No alerts for this drone this cycle — threat has cleared; stop strobe.
            await _algo.clear()
            _algo.clear_drone_state(drone_id)

    async def evaluate_heartbeat(self, hb: NodeHeartbeat):
        """
        Evaluate a heartbeat for GPS jamming. Fires a MEDIUM alert when
        jamming_state is set and not 'ok'. Deduplicated per node_id with
        a 60 second suppression window.
        """
        self._cleanup_dedup()
        if not hb.jamming_state or hb.jamming_state == "ok":
            return

        key = ("gps_jamming", None, hb.node_id)
        now_ts = time.time()
        if now_ts - self._dedup[key] < self.settings.alert_dedup_window_s:
            return
        self._dedup[key] = now_ts

        await self._emit({
            "level":    "medium",
            "category": "gps_jamming",
            "title":    f"GPS jamming detected on {hb.node_id}",
            "description": (
                f"Node {hb.node_id} reports GPS jamming_state='{hb.jamming_state}'. "
                f"Position data from this node may be unreliable."
            ),
            "drone_id": None,
            "node_id":  hb.node_id,
            "lat":      hb.gps.get("lat"),
            "lon":      hb.gps.get("lon"),
        })

    async def node_offline(self, node_id: str):
        """Called by the status handler when a node goes offline."""
        await self._emit({
            "level": "medium",
            "category": "node_offline",
            "title": f"Sensor node offline — {node_id}",
            "description": f"Node {node_id} stopped sending heartbeats. Coverage gap may exist.",
            "drone_id": None,
            "node_id": node_id,
            "lat": None,
            "lon": None,
        })

    async def _emit(self, alert: dict):
        """Deduplicate, write to DB, and broadcast to WebSocket clients."""
        pool = await get_pool()
        async with pool.acquire() as conn:
            row = await conn.fetchrow("""
                INSERT INTO alerts (level, category, drone_id, node_id, title, description, lat, lon)
                VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
                RETURNING id, created_at, level, category, drone_id, node_id,
                          title, description, lat, lon, acknowledged
            """,
                alert["level"], alert["category"],
                alert.get("drone_id"), alert.get("node_id"),
                alert["title"], alert.get("description"),
                alert.get("lat"), alert.get("lon"),
            )

        log.info(f"Alert [{alert['level'].upper()}] {alert['title']}")

        # Push to WebSocket clients
        await self.broadcaster.broadcast_alert(dict(row))
        # NOTE: Algo 8128 strobe trigger is handled in evaluate() after the full
        # alert batch is processed, so we can determine the highest threat level.
